version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  localstack:
    image: localstack/localstack
    container_name: s3
    ports:
      - "4566:4566"
    environment:
      - "SERVICES=s3"
    volumes:
      - "./localstack_init:/docker-entrypoint-initaws.d"
